base_dir = "path/to/where/you/run/aspect/input"
experiment_dirs = ["out_drex_olivineA/"]
compressed = false

[pole_figures]
    elastisity_header = false #not yet implemented
    small_figure = true
    no_description_text = false
    color_scale = "Batlow"
    times = [1.0,1e5,3e5]
    particle_ids = [0]
    axes = ["AAxis","BAxis","CAxis"]
    minerals = ["Olivine","Enstatite"]
    grain_data_file_prefix = "weighted_CPO"
    particle_data_dir = "particles_cpo"
    