#!/usr/bin/env python3
"""Run one closed CLIMBER-X, ASPECT, and Fastscape physical feedback cycle."""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import time
from pathlib import Path

import numpy as np


COOKBOOK = Path(__file__).resolve().parent
ASPECT_SOURCE = COOKBOOK.parents[1]
INSTALLATION = ASPECT_SOURCE.parent.parent
EXCHANGE_TOOL = (
    ASPECT_SOURCE / "contrib/coupling/climberx_fastscape/surface_exchange.py"
)
PLOT_TOOL = COOKBOOK / "plot_physical_loop.py"
sys.path.insert(0, str(EXCHANGE_TOOL.parent))
from surface_exchange import read_exchange  # noqa: E402


def free_memory_percent() -> int | None:
    result = subprocess.run(["memory_pressure"], capture_output=True, text=True)
    match = re.search(r"System-wide memory free percentage: (\d+)%", result.stdout)
    return int(match.group(1)) if match else None


def run_monitored(
    command, working_directory, log_path, environment, minimum_free_percent
):
    available = free_memory_percent()
    if available is not None and available < minimum_free_percent:
        raise RuntimeError(f"not starting because only {available}% of memory is free")
    log_path.parent.mkdir(parents=True, exist_ok=True)
    with log_path.open("w", encoding="utf-8") as log:
        process = subprocess.Popen(
            command,
            cwd=working_directory,
            env=environment,
            stdout=log,
            stderr=subprocess.STDOUT,
            start_new_session=True,
        )
        while process.poll() is None:
            time.sleep(5)
            available = free_memory_percent()
            if available is not None and available < minimum_free_percent:
                os.killpg(process.pid, signal.SIGTERM)
                try:
                    process.wait(timeout=10)
                except subprocess.TimeoutExpired:
                    os.killpg(process.pid, signal.SIGKILL)
                    process.wait()
                raise RuntimeError(
                    f"stopped {command[0]} because free memory fell to {available}%"
                )
        if process.returncode:
            raise subprocess.CalledProcessError(process.returncode, command)


def prepare_climate_case(template: Path, destination: Path, executable: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    for namelist in template.glob("*.nml"):
        shutil.copy2(namelist, destination / namelist.name)
    for name in ("input", "maps", "restart"):
        source, target = template / name, destination / name
        if target.exists() or target.is_symlink():
            target.unlink()
        target.symlink_to(source.resolve(), target_is_directory=True)
    target = destination / "climber.x"
    if target.exists() or target.is_symlink():
        target.unlink()
    target.symlink_to(executable.resolve())


def run_climate(
    case, output_exchange, topography_exchange, climber_library, minimum_free_percent
):
    environment = os.environ.copy()
    paths = [str(climber_library), "/opt/homebrew/Cellar/netcdf/4.9.3/lib"]
    if environment.get("DYLD_LIBRARY_PATH"):
        paths.append(environment["DYLD_LIBRARY_PATH"])
    environment["DYLD_LIBRARY_PATH"] = ":".join(paths)
    environment["OMP_NUM_THREADS"] = "1"
    environment["CLIMBERX_CLIMATE_EXCHANGE_FILE"] = str(output_exchange.resolve())
    if topography_exchange is not None:
        environment["CLIMBERX_TOPOGRAPHY_EXCHANGE_FILE"] = str(
            topography_exchange.resolve()
        )
    run_monitored(
        ["./climber.x"], case, case / "climber.log", environment, minimum_free_percent
    )
    log_text = (case / "climber.log").read_text(encoding="utf-8", errors="replace")
    if (
        not output_exchange.is_file()
        or "run aborted because of instabilities" in log_text
    ):
        raise RuntimeError(
            f"CLIMBER-X did not complete a stable exchange; see {case / 'climber.log'}"
        )


def write_aspect_parameters(path: Path, output_directory: Path, fields: Path) -> None:
    base = (
        INSTALLATION
        / "aspect_fatscapecc/tests/fastscape_cpp_global_climate_geodynamics.prm"
    ).resolve()
    data = fields.resolve()
    path.write_text(
        f"""# Generated by the physical-loop cookbook.
include {base}

set Output directory   = {output_directory.resolve()}
set Resume computation = false
set End time           = 20
set Maximum time step  = 10

subsection Geometry model
  subsection Initial topography model
    set Model name = ascii data
    subsection Ascii data model
      set Data directory = {data}/
      set Data file name = surface-topography.txt
    end
  end
end

subsection Mesh deformation
  subsection FastScape surface evolution
    set Initial relief                        = 0
    set Advect surface state                  = true
    set Hillslope diffusion coefficient       = 1e8
    set Marine sediment transport coefficient = 1e7
    set Marine sediment porosity              = 0.4
    set Marine transport depth scale          = 2500
    set Spatial erosion strength file         = {data}/erosion-strength.txt
    set Spatial surface runoff file           = {data}/surface-runoff.txt
    set Spatial ice thickness file            = {data}/ice-thickness.txt
    set Spatial basal ice velocity file        = {data}/basal-ice-velocity.txt
    set Glacial erosion coefficient            = 1e-5
    set Glacial velocity exponent              = 1
    set Minimum ice thickness                  = 10
    set Enable true polar wander               = true
    set Include ice load in true polar wander  = true
    set Rotational bulge inertia difference    = 2.6e35
    set Polar wander relaxation time           = 1e6
    set Maximum polar wander rate              = 10
    set Enable degree two self gravity         = true
    set Elastic degree two load Love number    = -0.3
    set Fluid degree two load Love number      = -0.9
    set Self gravity relaxation time           = 10000
    set Initialize self gravity in equilibrium = true
  end
end
""",
        encoding="utf-8",
    )


def convert_climate(exchange: Path, fields: Path) -> None:
    fields.mkdir(parents=True, exist_ok=True)
    command = [sys.executable, str(EXCHANGE_TOOL), "climate-to-aspect", str(exchange)]
    for option, name in (
        ("--surface-topography", "surface-topography.txt"),
        ("--erosion-strength", "erosion-strength.txt"),
        ("--surface-runoff", "surface-runoff.txt"),
        ("--ice-thickness", "ice-thickness.txt"),
        ("--basal-ice-velocity", "basal-ice-velocity.txt"),
    ):
        command.extend((option, str(fields / name)))
    subprocess.run(command, check=True)


def newest(path: Path, pattern: str) -> Path:
    candidates = sorted(path.rglob(pattern))
    if not candidates:
        raise RuntimeError(f"no {pattern} was written below {path}")
    return candidates[-1]


def surface_statistics(surface: Path) -> dict[str, float]:
    with surface.open(newline="", encoding="utf-8") as stream:
        rows = list(csv.DictReader(stream))
    result = {}
    for column in (
        "elevation_change_m",
        "glacial_erosion_m",
        "sediment_flux_m3_per_year",
        "marine_sediment_flux_m3_per_year",
    ):
        values = np.array([float(row[column]) for row in rows])
        result[f"maximum_{column}"] = float(np.max(values))
        result[f"sum_{column}"] = float(np.sum(values))
    return result


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output", type=Path, default=COOKBOOK / "output-physical-loop"
    )
    parser.add_argument("--minimum-free-memory-percent", type=int, default=15)
    arguments = parser.parse_args()
    climate_root = INSTALLATION / "aspect_ClimberX"
    template = climate_root / "tests/yelmo-active-diva"
    climate_executable = climate_root / "sources/climber-x/climber.x"
    aspect_executable = (
        INSTALLATION / "aspect_fatscapecc/builts/fastscape-release/aspect-release"
    )
    for required in (template, climate_executable, aspect_executable, EXCHANGE_TOOL):
        if not required.exists():
            parser.error(f"required local installation is missing: {required}")

    output = arguments.output.resolve()
    baseline_case, feedback_case = (
        output / "climate-baseline",
        output / "climate-feedback",
    )
    baseline_exchange = output / "baseline-climate.cxe"
    feedback_exchange = output / "feedback-climate.cxe"
    topography_exchange = output / "returned-topography.cxe"
    aspect_output, fields = output / "aspect-fastscape", output / "aspect-input"

    prepare_climate_case(template, baseline_case, climate_executable)
    run_climate(
        baseline_case,
        baseline_exchange,
        None,
        climate_root / "local/lib",
        arguments.minimum_free_memory_percent,
    )
    convert_climate(baseline_exchange, fields)
    parameter_file = output / "physical-loop.prm"
    write_aspect_parameters(parameter_file, aspect_output, fields)
    run_monitored(
        [str(aspect_executable), str(parameter_file)],
        INSTALLATION / "aspect_fatscapecc/tests",
        output / "aspect.log",
        os.environ.copy(),
        arguments.minimum_free_memory_percent,
    )

    surface = newest(aspect_output, "surface-*.csv")
    command = [
        sys.executable,
        str(EXCHANGE_TOOL),
        "surface-to-climate",
        "--surface",
        str(surface),
        "--climate",
        str(baseline_exchange),
        "--output",
        str(topography_exchange),
    ]
    polar_history = next(iter(aspect_output.rglob("true_polar_wander.csv")), None)
    if polar_history is not None:
        command.extend(("--polar-wander-history", str(polar_history)))
    subprocess.run(command, check=True)

    prepare_climate_case(template, feedback_case, climate_executable)
    run_climate(
        feedback_case,
        feedback_exchange,
        topography_exchange,
        climate_root / "local/lib",
        arguments.minimum_free_memory_percent,
    )
    plot_environment = os.environ.copy()
    plot_environment["MPLCONFIGDIR"] = str(output / ".matplotlib")
    subprocess.run(
        [
            sys.executable,
            str(PLOT_TOOL),
            "--baseline",
            str(baseline_exchange),
            "--feedback",
            str(feedback_exchange),
            "--topography",
            str(topography_exchange),
            "--surface",
            str(surface),
            "--output",
            str(output / "physical-loop-summary.png"),
        ],
        check=True,
        env=plot_environment,
    )
    summary = surface_statistics(surface)
    baseline = read_exchange(baseline_exchange)
    feedback = read_exchange(feedback_exchange)
    for field in (
        "precipitation_rate",
        "surface_temperature",
        "ice_thickness",
        "basal_ice_velocity",
    ):
        difference = feedback.fields[field] - baseline.fields[field]
        summary[f"maximum_absolute_{field}_change"] = float(np.max(np.abs(difference)))
    summary.update(
        {
            "baseline_exchange": str(baseline_exchange),
            "feedback_exchange": str(feedback_exchange),
            "returned_topography": str(topography_exchange),
            "surface_result": str(surface),
            "polar_wander_history": str(polar_history) if polar_history else None,
        }
    )
    (output / "summary.json").write_text(
        json.dumps(summary, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
